version: '2.1'

services:

  # serverlessapp:
  #   build: .
  #   volumes:
  #     - .:/src
  #     - nodemodules:/src/node_modules
  #   restart: on-failure
  #   ports:
  #     - 3000:3000
  #   links:
  #     - mysql
  #   depends_on:
  #     - mysql
  #   networks:
  #     - db-net
    # environment:

  mysql:
    image: mysql:5.7
    volumes:
        - mysql-db:/var/lib/mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: toctoc_admin
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: toctoc
      MYSQL_ROOT_PASSWORD: root
    ports:
        - 3306:3306
    # networks:
    #   - db-net

volumes:
  mysql-db:
  # nodemodules: {}

# networks:
#   db-net:
