checkWaitListPosition:
  handler: src/modules/checkWaitListPosition/index.checkWaitListPosition
  events:
    - http:
        path: checkWaitListPosition/{id}
        method: get
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    # include:
    #   - src/modules/checkWaitListPosition/**

    # patterns:
    #   - node_modules/**

    patterns:
      - "!src/modules/**"
      - src/modules/checkWaitListPosition/**
      - node_modules/**
