  contatosSendEmail:
    handler: src/modules/contatosSendEmail/index.contatosSendEmail
    
    events:
      - http:
          path: contatosSendEmail
          method: post
          cors: true
          authorizer: aws_iam
    # layers:
    #   - { Ref: NodeModulesLambdaLayer }
    package:
      individually: true

      patterns:
        - '!src/modules/**'
        - src/modules/contatosSendEmail/**
        - node_modules/**
