createSubscriptionStripe:
  handler: src/modules/createSubscriptionStripe/index.createSubscriptionStripe
  vpc: ~
  events:
    - http:
        path: createSubscriptionStripe
        method: post
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/createSubscriptionStripe/**
      - node_modules/**
