deleteCategoria:
  handler: src/modules/deleteCategoria/index.deleteCategoria
  events:
    - http:
        path: deleteCategoria/{id}
        method: delete
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/deleteCategoria/**
      - node_modules/**