  deleteMesaTravar:
    handler: src/modules/deleteMesaTravar/index.deleteMesaTravar
    events:
      - http:
          path: deleteMesaTravar/{id}
          method: delete
          cors: true
          authorizer: aws_iam

    # layers:
    #   - { Ref: NodeModulesLambdaLayer }
    package:
      individually: true

      patterns:
        - '!src/modules/**'
        - src/modules/deleteMesaTravar/**
        - node_modules/**
