findEventsByColab:
  handler: src/modules/findEventsByColab/index.findEventsByColab
  events:
    - http:
        path: findEventsByColab
        method: get
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/findEventsByColab/**
      - node_modules/**
