findAllCity:
  handler: src/modules/findAllCity/index.findAllCity
  events:
    - http:
        path: findAllCity/{uf}
        method: get
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
      individually: true

      patterns:
        - "!src/modules/**"
        - src/modules/findAllCity/**
        - node_modules/**
