findNextEvents:
  handler: src/modules/findNextEvents/index.findNextEvents
  events:
    - http:
        path: findNextEvents
        method: get
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/findNextEvents/**
      - node_modules/**
