findAllUF:
  handler: src/modules/findAllUf/index.findAllUF
  events:
    - http:
        path: findAllUF
        method: get
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
      individually: true

      patterns:
        - "!src/modules/**"
        - src/modules/findAllUf/**
        - node_modules/**
