findEvents:
  handler: src/modules/findEvents/index.findEvents
  events:
    - http:
        path: findEvents
        method: get
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/findEvents/**
      - node_modules/**
