findReserva:
  handler: src/modules/findReserva/index.findReserva
  events:
    - http:
        path: findReserva/{id}
        method: get
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/findReserva/**
      - node_modules/**
