findConvidadosColab:
  handler: src/modules/findConvidadosColab/index.findConvidadosColab
  events:
    - http:
        path: findConvidadosColab/{idEvento}
        method: get
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/findConvidadosColab/**
      - node_modules/**
