getButtonsLinkBio:
  handler: src/modules/getButtonsLinkBio/index.getButtonsLinkBio
  events:
    - http:
        path: getButtonsLinkBio
        method: get
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/getButtonsLinkBio/**
      - node_modules/**
