getColaboradorEvento:
  handler: src/modules/getColaboradorEvento/index.getColaboradorEvento
  events:
    - http:
        path: colaboradorEvento/{id}
        method: get
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/getColaboradorEvento/**
      - node_modules/**
