getConvidados:
  handler: src/modules/getConvidados/index.getConvidados
  events:
    - http:
        path: getConvidados/{idEvento}
        method: get
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/getConvidados/**
      - node_modules/**
