getEventoById:
  handler: src/modules/getEventoById/index.getEventoById
  events:
    - http:
        path: getEventoById/{id}
        method: get
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/getEventoById/**
      - node_modules/**
