getListaTipos:
  handler: src/modules/getListaTipos/index.getListaTipos
  events:
    - http:
        path: getListaTipos
        method: get
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/getListaTipos/**
      - node_modules/**
