getMailing:
  handler: src/modules/getMailing/index.getMailing
  events:
    - http:
        path: mailing
        method: get
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/getMailing/**
      - node_modules/**
