getPedidos:
  handler: src/modules/getPedidos/index.getPedidos
  events:
    - http:
        path: getPedidos
        method: get
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/getPedidos/**
      - node_modules/**
