getReservasMesas:
  handler: src/modules/getReservasMesas/index.getReservasMesas
  events:
    - http:
        path: getReservasMesas/{idEvento}
        method: get
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/getReservasMesas/**
      - node_modules/**
