getSubscriptionActive:
  handler: src/modules/getSubscriptionActive/index.stripeSubscription
  events:
    - http:
        path: getSubscriptionActive
        method: get
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/getSubscriptionActive/**
      - node_modules/**
