getTable:
  handler: src/modules/getTable/index.getTable
  events:
    - http:
        path: getTable
        method: get
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/getTable/**
      - node_modules/**
