getVerifyHash:
  handler: src/modules/getVerifyHash/index.getVerifyHash
  events:
    - http:
        path: getVerifyHash/{hash}
        method: get
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/getVerifyHash/**
      - node_modules/**
