insertFilaDeEsperaSemCognito:
  handler: src/modules/insertFilaDeEsperaSemCognito/index.insertFilaDeEsperaSemCognito
  events:
    - http:
        path: insertFilaDeEsperaSemCognito
        method: post
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/insertFilaDeEsperaSemCognito/**
      - node_modules/**
