  insertUser:
    handler: src/modules/insertUser/index.insertUser
    events:
      - http:
          path: user
          method: post
          cors: true
    # layers:
    #   - { Ref: NodeModulesLambdaLayer }
    package:
      individually: true

      patterns:
        - '!src/modules/**'
        - src/modules/insertUser/**
        - node_modules/**
