insertConvidadoPromover:
  handler: src/modules/insertConvidadoPromover/index.insertConvidadoPromover
  events:
    - http:
        path: insertConvidadoPromover
        method: post
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/insertConvidadoPromover/**
      - node_modules/**
