insertReservaMesa:
  handler: src/modules/insertReservaMesa/index.insertReservaMesa
  events:
    - http:
        path: insertReservaMesa
        method: post
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/insertReservaMesa/**
      - node_modules/**
