  insertAniversariosForm:
    handler: src/modules/insertAniversariosForm/index.insertAniversariosForm
    events:
      - http:
          path: insertAniversariosForm
          method: post
          cors: true
    # layers:
    #   - { Ref: NodeModulesLambdaLayer }
    package:
      individually: true

      patterns:
        - '!src/modules/**'
        - src/modules/insertAniversariosForm/**
        - node_modules/**
