insertConvidado:
  handler: src/modules/insertConvidado/index.insertConvidado
  events:
    - http:
        path: insertConvidado
        method: post
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/insertConvidado/**
      - node_modules/**
