insertInteressados:
  handler: src/modules/insertInteressados/index.insertInteressados
  events:
    - http:
        path: insertInteressados
        method: post
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/insertInteressados/**
      - node_modules/**
