insertCenarioMesas:
  handler: src/modules/insertCenarioMesas/index.insertCenarioMesas
  events:
    - http:
        path: insertCenarioMesas
        method: post
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/insertCenarioMesas/**
      - node_modules/**
