insertSubEvento:
  handler: src/modules/insertSubEvento/index.insertSubEvento
  events:
    - http:
        path: insertSubEvento
        method: post
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/insertSubEvento/**
      - node_modules/**
