insertButtonsClick:
  handler: src/modules/insertButtonsClick/index.insertButtonsClick
  events:
    - http:
        path: insertButtonsClick/{id}
        method: post
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/insertButtonsClick/**
      - node_modules/**
