insertReservationMercadoPago:
  handler: src/modules/insertReservationMercadoPago/index.insertReservationMercadoPago
  vpc: ~
  events:
    - http:
        path: insertReservationMercadoPago
        method: post
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/insertReservationMercadoPago/**
      - node_modules/**
