insertReservaMesaUser:
  handler: src/modules/insertReservaMesaUser/index.insertReservaMesaUser
  events:
    - http:
        path: insertReservaMesaUser
        method: post
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/insertReservaMesaUser/**
      - node_modules/**
