insertBlacklist:
  handler: src/modules/insertBlacklist/index.insertBlacklist
  events:
    - http:
        path: insertBlacklist
        method: post
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/insertBlacklist/**
      - node_modules/**
