  insertAvaliacao:
    handler: src/modules/insertAvaliacao/index.insertAvaliacao
    events:
      - http:
          path: insertAvaliacao
          method: post
          cors: true
    # layers:
    #   - { Ref: NodeModulesLambdaLayer }
    package:
      individually: true

      patterns:
        - '!src/modules/**'
        - src/modules/insertAvaliacao/**
        - node_modules/**
