postPedidoMesa:
  handler: src/modules/postPedidoMesa/index.postPedidoMesa
  events:
    - http:
        path: postPedidoMesa
        method: post
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/postPedidoMesa/**
      - node_modules/**
