postNotificacoes:
  handler: src/modules/postNotificacoes/index.postNotificacoes
  events:
    - http:
        path: postNotificacoes
        method: post
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/postNotificacoes/**
      - node_modules/**
