updateFuncoesColabFixo:
  handler: src/modules/updateFuncoesColabFixo/index.updateFuncoesColabFixo
  events:
    - http:
        path: updateFuncoesColabFixo
        method: patch
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/updateFuncoesColabFixo/**
      - node_modules/**
