updateLista:
  handler: src/modules/updateLista/index.updateLista
  events:
    - http:
        path: updateLista/{id}
        method: patch
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/updateLista/**
      - node_modules/**
