updateButtonsDGLinkBio:
  handler: src/modules/updateButtonsDGLinkBio/index.updateButtonsDGLinkBio
  events:
    - http:
        path: updateButtonsDGLinkBio/{id}
        method: patch
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/updateButtonsDGLinkBio/**
      - node_modules/**
