updateAniversario:
  handler: src/modules/updateAniversario/index.updateAniversario
  events:
    - http:
        path: updateAniversario
        method: patch
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/updateAniversario/**
      - node_modules/**
