updateFilaDeEspera:
  handler: src/modules/updateFilaDeEspera/index.updateFilaDeEspera
  events:
    - http:
        path: updateFilaDeEspera/{id}
        method: patch
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/updateFilaDeEspera/**
      - node_modules/**
