updateReservaMesa:
  handler: src/modules/updateReservaMesa/index.updateReservaMesa
  events:
    - http:
        path: updateReservaMesa/{id}
        method: patch
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/updateReservaMesa/**
      - node_modules/**
