updateUser:
  handler: src/modules/updateUser/index.updateUser
  events:
    - http:
        path: user
        method: patch
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/updateUser/**
      - node_modules/**
