updateCardapio:
  handler: src/modules/updateCardapio/index.updateCardapio
  events:
    - http:
        path: updateCardapio
        method: patch
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/updateCardapio/**
      - node_modules/**