updateCategoria:
  handler: src/modules/updateCategoria/index.updateCategoria
  events:
    - http:
        path: updateCategoria/{id}
        method: patch
        cors: true
        authorizer: aws_iam
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/updateCategoria/**
      - node_modules/**