uploadImageProduct:
  handler: src/modules/uploadImageProduct/index.uploadImageProduct
  events:
    - http:
        path: uploadImageProduct
        method: post
        cors: true
        authorizer: auth
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/uploadImageProduct/**
      - node_modules/**