VerifyUser:
  handler: src/modules/VerifyUser/index.VerifyUser
  events:
    - http:
        path: VerifyUser/{documento}/{slug}
        method: get
        cors: true
  # layers:
  #   - { Ref: NodeModulesLambdaLayer }
  package:
    individually: true

    patterns:
      - "!src/modules/**"
      - src/modules/VerifyUser/**
      - node_modules/**
